language: node_js
dist: trusty
node_js:
  - "6.5"
branches:
  only:
  - master
before_script:
  - phantomjs --webdriver=4444 &
  - npm install -g gulp-cli
script:
  - gulp build
  - npm run unittest
  - npm run integrationtest
  - sleep 3
deploy:
  provider: heroku
  app: legendary-quest
  api_key:
    secure: HV389T5DqAe4dcxIaCOa30Bb4+1IqDUFQ5+N20evVoyWJc6BFj0zOE2qkR+v1AzPql2YMb0aUn7MV5eSnDNETNTp05xO2jY2OZCnTgerHrvFZG40snW/LbM+FSZfylTcN/KhtcvvAm/WlqG0fBPufo2ZT6SsbLzLZUtADUg0lHNZ5YqcwVmZMJXFRGvP9PNDP5o7A+tgIlAw4w6EMh1wrIFV/+JR1ie0KB2C4Ithx1/z17aEroIxt625r2vmRKlkOoe8AoMd9SRHpPwE1y811lcV8tlx3Vn0n21nnJz3TUF/UVNyOHuBa1X/LIDtKp1hTN3w/0EJ2a1pMtoSKy4f4KD8R+ddG/T5xbVxrdQYhpjHktXKJdGM0GWzj6LzyjJW0urthrgpVBdo540LroaOdbfWJUhbXxYQd0UVzfFyToDV6oAECa0exLNiH2+bA/goqjH1ZNuGhm3UOsPovrxB8Eg/hK8XAtCP7oq09P0dJD2kFvJVIzyS+ibgjE0gwia4XOCReCju3vGkJmJg8epJAdclyFj+SXoLj/Dqz8n7cSMAek/u3yx7ngdD9lQaS8t72laEyZ6xCUB4ptOVX2u0/SxQN6zdKfwMS8hIKNkbvCpGAbODnP9+4maATOyi/dxXoOER0pxQGLPw+nWKeAl3rlqR/EB6JU3232ZAH0B3uQ0=