language: node_js
node_js:
  - "6"
deploy:
  provider: heroku
  app: legendary-quest
  api_key:
    secure: HV389T5DqAe4dcxIaCOa30Bb4+1IqDUFQ5+N20evVoyWJc6BFj0zOE2qkR+v1AzPql2YMb0aUn7MV5eSnDNETNTp05xO2jY2OZCnTgerHrvFZG40snW/LbM+FSZfylTcN/KhtcvvAm/WlqG0fBPufo2ZT6SsbLzLZUtADUg0lHNZ5YqcwVmZMJXFRGvP9PNDP5o7A+tgIlAw4w6EMh1wrIFV/+JR1ie0KB2C4Ithx1/z17aEroIxt625r2vmRKlkOoe8AoMd9SRHpPwE1y811lcV8tlx3Vn0n21nnJz3TUF/UVNyOHuBa1X/LIDtKp1hTN3w/0EJ2a1pMtoSKy4f4KD8R+ddG/T5xbVxrdQYhpjHktXKJdGM0GWzj6LzyjJW0urthrgpVBdo540LroaOdbfWJUhbXxYQd0UVzfFyToDV6oAECa0exLNiH2+bA/goqjH1ZNuGhm3UOsPovrxB8Eg/hK8XAtCP7oq09P0dJD2kFvJVIzyS+ibgjE0gwia4XOCReCju3vGkJmJg8epJAdclyFj+SXoLj/Dqz8n7cSMAek/u3yx7ngdD9lQaS8t72laEyZ6xCUB4ptOVX2u0/SxQN6zdKfwMS8hIKNkbvCpGAbODnP9+4maATOyi/dxXoOER0pxQGLPw+nWKeAl3rlqR/EB6JU3232ZAH0B3uQ0=
addons:
  sauce_connect:
    username: "RedGlow"
    access_key:
      secure: HtFxTw4ee0RJVCaWN5P2RTImDl42mvF3hBk/XNjec98YWHNQpruRes7OSndT7pOmuYsADjMcPuDxVfm9Wlt6v2xZf9p1wprMdtwPLk6fqKkpG4YBSVriCOV2ijNyDK84Gcemn1yX0LW/aMC4SCQEc/XKfD1H22eA5T2IcKbb1GcQqCFR7yHAOXlS6EgvlEAn3/+ze+Agv0z4IEL39bGTWyi0ta4vCnxc1s+o3SUnzyjARY8MmEmk5NCbN8c5vbUG/6rPdEU3n47OH6hK5nFoG4mqcyxIW2pLDA6k868lu/BVBz6+RcWePwuG0h9B7vMbMMtTjZii+JqNs08x4eAZ+Tbh1u2jMrsH9IodchwxNDDkOgETe1mJganUZU7Np7aVpX4bJcOJVKRdx0X7oWIRU169BWbcIKGgun4gtWEY6InzbawgPv4HCMUCBKwFE+20MQrq2i6rA9kvTc55SvJ1lwm2TK95pN6er6zVuPx2lIouD7c3OXyASLc1pj6r0VWF1ClCyHmpT/LGqLhBfGn7WSCXvp/pZBxm4ykSCUtfaLf4oJGuW8b/O2/3n0W/DCEWgCUCu9xCGuExBEndz2Zwnl8pEJ2aExn2ubqAfXy+gwZtM+R5UwQz0L84Xuk7tnu7/Wa8PeHVX7fno3GgclofwLCW3Cq9y6cMRbtbUOpKRRo=